name: CI

on:
  push:
  pull_request:

defaults:
  run:
    # PowerShell's behavior for -flag=value is undesirable, so run all commands with bash.
    shell: bash

jobs:

  test:
    name: Run tests (${{ matrix.os }}, ${{ matrix.go-version }})
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        go-version: [1.23.x]
        include:
          # Test old supported Go version
          - os: ubuntu
            go-version: 1.22.x
    env:
      ELVISH_TEST_TIME_SCALE: 20
    runs-on: ${{ matrix.os }}-latest
    steps:
    # autocrlf is problematic for fuzz testdata.
    - name: Turn off autocrlf
      if: matrix.os == 'windows'
      run: git config --global core.autocrlf false
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Test with race detection
      run: |
        go test -race ./...
        cd website; go test -race ./...

  release:
    name: Run GoReleaser
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.x
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  emulated_tests:
    name: Run tests (emulated ${{ matrix.go-arch }})
    strategy:
      matrix:
        go-arch: [riscv64, s390x]
    env:
      ELVISH_TEST_TIME_SCALE: 20
      GOARCH: ${{ matrix.go-arch }}
    runs-on: ubuntu-latest
    steps:
    - name: Set up emulator
      run: |
        sudo apt update
        sudo apt install binfmt-support qemu-user-static
        update-binfmts --display
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.x
    - name: Test with emulator
      run: |
        go test ./...
        cd website; go test ./...

  # The purpose of running benchmarks in GitHub Actions is primarily to ensure
  # that the benchmark code runs and doesn't crash. GitHub Action runners don't
  # have a stable enough environment to produce reliable benchmark numbers.
  benchmark:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.x
    - name: Run benchmarks
      run: go test -bench=. -run='^$' ./...

  checks:
    name: Run checks
    # Most checks do not rely on the OS, but some (like check-gen) do. To ensure
    # maximal coverage, we run all of the checks on the three main OSes.
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    runs-on: ${{ matrix.os }}-latest
    steps:
    # autocrlf is problematic for check-fmt-go.
    - name: Turn off autocrlf
      if: matrix.os == 'windows'
      run: git config --global core.autocrlf false
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.x
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install tools
      run: |
        go install golang.org/x/tools/cmd/stringer@latest
        go install golang.org/x/tools/cmd/goimports@latest
        # Keep the versions of staticcheck and codespell in sync with docs/workflows.md
        go install honnef.co/go/tools/cmd/staticcheck@v0.6.0
        pip install codespell==2.3.0
    - name: Run checks
      run: make all-checks
